---
- name: "Install clock software"
  hosts: rack12
  gather_facts: false
  vars:
    working: /opt/aclock
    matrix_src_hash: a3eea997a9254b83ab2de97ae80d83588f696387
  tasks:
    - name: "Prepare system"
      when: "quick is undefined"
      ansible.builtin.import_tasks:
        file: tasks/sysprep.yaml
    - name: "Install RGB matrix software"
      when: "quick is undefined"
      ansible.builtin.import_tasks:
        file: tasks/install-matrix.yaml
    - name: "Copy opt contents"
      with_items:
        - aclock.py
        - run-aclock.sh
        - requirements.txt
        - 5x13.bdf
      ansible.builtin.copy:
        src: "{{ item }}"
        mode: '0555'
        dest: "{{ working }}/{{ item }}"
    - name: "Install Python dependencies"
      when: "quick is undefined"
      ansible.builtin.shell:
        chdir: "{{ working }}"
        cmd: 'python3 -m venv env && . env/bin/activate && python3 -m pip install -r requirements.txt'
    - name: "Install aclock unit"
      become: true
      ansible.builtin.copy:
        src: "aclock.service"
        dest: /etc/systemd/system/aclock.service
    - name: "Start/restart clock"
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        unit: aclock.service
        enabled: true
        state: restarted


