- name: "Download / update repository"
  ansible.builtin.git:
    depth: 1
    dest: "{{ working }}/matrix/src"
    repo: "https://github.com/hzeller/rpi-rgb-led-matrix"
    version: "{{ matrix_src_hash }}"
- name: "Install build deps"
  become: true
  ansible.builtin.apt:
    pkg:
      - make
      - python3-distutils
      - python3-dev
- name: "Build"
  ansible.builtin.command:
    chdir: "{{ working }}/matrix/src"
    cmd: "make build-python"
  # TODO: Initialize virtual environment;
  # then install Python bindings into it
- name: "Install Python bindings"
  become: true
  ansible.builtin.command:
    chdir: "{{ working }}/matrix/src"
    cmd: "make install-python"
- name: "Build demos"
  ansible.builtin.command:
    chdir: "{{ working }}/matrix/src/examples-api-use"
    cmd: "make all"

